language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements/ci.txt --use-mirrors"
# command to run tests
script: nosetests
# run deploy script on server
notifications:
  webhooks:
    urls:
       - http://serve.webstandardsdays.ru/
    on_sucess: always
    on_failure: never
